REF_GENOTYPE: "Hilliard"
REF_FASTA: "/project/gbru_wheat2/ref/NCBI_MWillman/Taes_Hilliard_1.1.fasta"
FASTQ_DIR: "/90daydata/gbru_wheat2/Exomecluster/data/merged_by_line"
PICARD_JAR: "/project/gbru_wheat2/fhb/conda/exomecluster_env/share/picard-3.2.0-0/picard.jar"
GATK_SIF: "/project/gbru_wheat2/fhb/singularity/gatk_latest.sif"
INTERVALS:
  - "chr1A"
  - "chr1B"
  - "chr1D"
  - "chr2A"
  - "chr2B"
  - "chr2D"
  - "chr3A"
  - "chr3B"
  - "chr3D"
  - "chr4A"
  - "chr4B"
  - "chr4D"
  - "chr5A"
  - "chr5B"
  - "chr5D"
  - "chr6A"
  - "chr6B"
  - "chr6D"
  - "chr7A"
  - "chr7B"
  - "chr7D"
