REF_GENOTYPE: "Hilliard"
REF_FASTA: "/90daydata/gbru_wheat2/Snakemake_linted/Hilliard/1_Assembly/Hilliard_scaffold_assembly.fa"
FASTQ_DIR: "/90daydata/gbru_wheat2/Exomecluster/data/raw"
PICARD_JAR: "/project/gbru_wheat2/fhb/conda/exomecluster_env/share/picard-3.2.0-0/picard.jar"
GATK_SIF: "/project/gbru_wheat2/fhb/singularity/gatk_latest.sif"
INTERVALS:
  - "chr1A_RagTag"
  - "chr1A_RagTag"
  - "chr1B_RagTag"
  - "chr1D_RagTag"
  - "chr2A_RagTag"
  - "chr2B_RagTag"
  - "chr2D_RagTag"
  - "chr3A_RagTag"
  - "chr3B_RagTag"
  - "chr3D_RagTag"
  - "chr4A_RagTag"
  - "chr4B_RagTag"
  - "chr4D_RagTag"
  - "chr5A_RagTag"
  - "chr5B_RagTag"
  - "chr5D_RagTag"
  - "chr6A_RagTag"
  - "chr6B_RagTag"
  - "chr6D_RagTag"
  - "chr7A_RagTag"
  - "chr7B_RagTag"
  - "chr7D_RagTag"
  